### ISSUE TITLE
Feature: Support redirects without saleschannel

### ISSUE THREAD

**Issue by amenk** [scope01-GmbH/ScopPlatformRedirecter#10]
We have saleschannels 

example.com/de
example.com/en

And want add a specific a redirect

example.com/foo -> example.com/de/foo

Can such a functionality be added?

Currently we get "No matching saleschannel found".

We tried adding a sales channel

example.com/ (Language setting = German)

which works, but then the language switch would also target example.com/produktname when switching from example.com/en/productname, so this workaround is not viable

**Comment by Dororo02** [comment]
In case you don't have a Sales Channel on the base domain, our Redirect Plugin is not the right tool to realize redirects to e.g. /de, as this would require you to add a very large number of Redirects (one for each page).

Instead we would recommend a .htaccess redirect for this use case, as this solution can handle the redirects generically. As an example, it could look like that:

```
    RewriteCond %{REQUEST_URI} !^/de/.*$
    RewriteCond %{REQUEST_URI} !^/en/.*$
    RewriteCond %{REQUEST_URI} !^/de/?$
    RewriteCond %{REQUEST_URI} !^/en/?$
    RewriteCond %{REQUEST_URI} !^/admin/.*$
    RewriteCond %{REQUEST_URI} !^/admin/?$
    RewriteCond %{REQUEST_URI} !^/api/.*$
    RewriteCond %{REQUEST_URI} !^/api/?$
    RewriteCond %{REQUEST_URI} !^/sitemap/.*$
    RewriteCond %{REQUEST_URI} !^/sitemap/?$
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-l
    RewriteRule  ^(.*)$ /de/$1 [L,R=301]
```

**Comment by amenk** [comment]
@Dororo02 we had the plan to have some specific redirects under `/` to a few landing pages, so this still might be helpful but I admit the case is quite niche.

We will probably use something like you suggested, but have different slugs per language and we use a browser-language detection in the `.htaccess`. So that does not work in all cases.

We can still set a redirect from /de/english-name to /de/german-name then and so on to fix it with a double redirect.
