### ISSUE TITLE
Shopware 6.4.6.1 Plugin 1.1.0 CSV Import not possible

### ISSUE THREAD

**Issue by michael-sfx** [scope01-GmbH/ScopPlatformRedirecter#2]
If one example entry is exported as CSV and the same file reimportet, I get the following message:

Fehler
Die gewählte Datei "redirects_1638543054.csv" hat ein nicht unterstütztes Format.
Bitte benutze eins der folgenden Formate: text/csv.

File:
```
id;source_url;target_url;http_code;enabled
9a70f2c5e38c4fd0a247f4a9add2bfb4;alt-test;neu-test;301;1
```

**Comment by timotrautmann** [comment]
@michael-sfx on which browser / version / os you have this issue?

**Comment by michael-sfx** [comment]
Hi it's Firefox 94.0.2 (64bit)
Win10 Home 21H1

**Comment by timotrautmann** [comment]
Thank you we will have a look at it.

**Comment by patrickpahlke03** [comment]
Could you please send us the original file as an attachment? We can't reproduce the issue.

**Comment by michael-sfx** [comment]
[redirects_1641376018.csv](https://github.com/scope01-GmbH/ScopPlatformRedirecter/files/7813842/redirects_1641376018.csv)

I can not test the original file. I already imported the date via SQL

**Comment by timotrautmann** [comment]
@michael-sfx we can no reproduce the issue save. The problem is, that the CSV file is exported as text/plain mime time instead of text/csv. Windows do a deeper validation so text/plain will rejected during upload.
We will do a investigation on it and fix this issue.

**Comment by v3ritas1989** [comment]
same issue! Encodings checked for Windows(CR LF) UTF-8. OF already in use files in other system that has samerequirements. As well as newly created csv and txt with example data. Created by Excel,Windows10,Notepadd++. Any solution?

**Comment by Dororo02** [comment]
@v3ritas1989 on which browser / version / shopware version / plugin version you have this issue? And could you please provide your .csv file so we could reproduce the issue?

**Comment by v3ritas1989** [comment]
Following file
[Artikelstamm6.csv](https://github.com/scope01-GmbH/ScopPlatformRedirecter/files/9289695/Artikelstamm6.csv)
I noticed this file can be imported on chrome but not on firefox. (Both current versions)
Allother files throw the same error on both browsers. Even simple files like
[test2.txt](https://github.com/scope01-GmbH/ScopPlatformRedirecter/files/9289738/test2.txt)

Though even on Chrome when it works it seems to be having problems displaying the rows of my file in creation of a new profile
Shopware is latest development.git
docker install on remote container(if that matters)
Edit: Interestingly this is probably a shopware error and not a plugin error as I am actually not using your plugin.
