### ISSUE TITLE
Regex / Platzhalter

### ISSUE THREAD

**Issue by timmoh** [scope01-GmbH/ScopPlatformRedirecter#4]
Nicht direkt ein Issue.
Aber wäre es möglich das Redirect Plugin um Platzhalter oder noch besser Regex zu erweitern?

Beispiel: der komplette Shop zieht von /verzeichnisA/shop zu /verzeichnisb/
Aktuell müsste man jeder Url einzeln hinterlegen. Mit einen Platzhalter könnte man zB.

alles von `verzeichnisA/shop/*` => `/verzeichnisb/` umleiten
oder als Regex
alles von `verzeichnisA/shop/(.*)` => `/verzeichnisb/$1` umleiten

Wobei die zweite Möglichkeit natürlich viel dynamischer ist...

**Comment by timotrautmann** [comment]
This functionality is not planned and will not be implemented currently.
This tasks were better implemented by a developer in an .htaccess file. 
Mistakes in the patterns may result in a not availability of the whole shop and the knowledge of patters were not very spreaded in the community of admin users.
