### ISSUE TITLE
Limit redirects to saleschannel or use a replacement variable

### ISSUE THREAD

**Issue by amenk** [scope01-GmbH/ScopPlatformRedirecter#5]
We have the following case, which might be an edge case: Our shop has multiple sales channel example.de and example.com and we want to redirect paths only of one saleschannels (example.de).

This works when specifying the full source URL https://example.de/old -> https://example.de/new in the plugin.

Now we want to avoid to hard code the sales channel domain, because we have different test platforms (dev, CI review apps and so on).

Is it possible to limit the redirects in another way per sales channel?  Or to have a replacement variable like {{saleschannelId-baseUrl}} Would this be a valid feature?

Possible workaround: When switching to the test platforms, run a SQL replace on the rewrites table to avoid the problems.

**Comment by Dororo02** [comment]
With the new version 2.3.0 it is now possible to select a sales channels for each redirect individually.

**Comment by amenk** [comment]
Perfect, thank you very much

**Comment by amenk** [comment]
Thanks again :-D 
I would also suggest to put the sales channel field in the first position of the form so it's clear that's about the source field.
