### ISSUE TITLE
URL encoding errors

### ISSUE THREAD

**Issue by fdi-imi** [scope01-GmbH/ScopPlatformRedirecter#6]
URLs containing special characters, such as German "umlaut" like _ä ö ü_, are causing problems during redirect imports or manual redirect entries.
The problem arises when these URLs are not properly encoded before being entered for redirects. When special characters are present in a URL, currently they can only be converted manually to their corresponding URL-encoded format, In the case of _ö_ the resulting format is _%C3%B6_.
Is there a way by your side to ensure that URL encoding is implemented automatically and consistenly whenever URLs with special characters are being used?

**Comment by Dororo02** [comment]
With Version 2.2.0 we had added a very similar feature, which can be enabled in the plugin configuration. With this feature enabled it is no longer necessary to convert special characters in the URLs for the redirect to be recognized correctly.

![Screenshot](https://github.com/scope01-GmbH/ScopPlatformRedirecter/assets/28844999/569ed9ac-c4bf-4f51-9cc0-f0e8bf946088)

Does this function make the problem obsolete?
