### ISSUE TITLE
error 400 code

### ISSUE THREAD

**Issue by PowerChaos** [scope01-GmbH/ScopPlatformRedirecter#7]
hi,
i get a error 400 code when i try to use the redirect
this is for shopware 6.6.3.1

see image of error
Thanky you
Greetings from PowerChaos
![image](https://github.com/scope01-GmbH/ScopPlatformRedirecter/assets/7650333/b0dc6f40-5f46-4a25-af63-3d334cd430b4)

**Comment by Dororo02** [comment]
Hi,

this error was due to a bug in Shopware 6.6.3 (https://issues.shopware.com/issues/NEXT-36813), which is fixed in Shopware 6.6.4.

Alternatively, we have provided a fix in our plugin version 3.0.1.
